// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBai7wOP8l_Sia-SWyiXvqZmwnL0YWCwfE',
    appId: '1:33909260846:web:1b916db809b3bba76055bf',
    messagingSenderId: '33909260846',
    projectId: 'firedetection-3d3d5',
    authDomain: 'firedetection-3d3d5.firebaseapp.com',
    storageBucket: 'firedetection-3d3d5.firebasestorage.app',
    measurementId: 'G-9XL3EHPDZR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMasx4UdS16A3OHKUKeaXvg9mvnqmsKvk',
    appId: '1:33909260846:android:915bd07fc19320c66055bf',
    messagingSenderId: '33909260846',
    projectId: 'firedetection-3d3d5',
    storageBucket: 'firedetection-3d3d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb8SM95vIMY_d4xw7rfVTYXkLcSO7wsEU',
    appId: '1:33909260846:ios:a5c231999429d1df6055bf',
    messagingSenderId: '33909260846',
    projectId: 'firedetection-3d3d5',
    storageBucket: 'firedetection-3d3d5.firebasestorage.app',
    iosBundleId: 'com.example.frontendv23',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDb8SM95vIMY_d4xw7rfVTYXkLcSO7wsEU',
    appId: '1:33909260846:ios:a5c231999429d1df6055bf',
    messagingSenderId: '33909260846',
    projectId: 'firedetection-3d3d5',
    storageBucket: 'firedetection-3d3d5.firebasestorage.app',
    iosBundleId: 'com.example.frontendv23',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBai7wOP8l_Sia-SWyiXvqZmwnL0YWCwfE',
    appId: '1:33909260846:web:b68d5a4dce068e576055bf',
    messagingSenderId: '33909260846',
    projectId: 'firedetection-3d3d5',
    authDomain: 'firedetection-3d3d5.firebaseapp.com',
    storageBucket: 'firedetection-3d3d5.firebasestorage.app',
    measurementId: 'G-6Z6SHVZQ48',
  );

}